name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "51363990-05d3b36d-97d6-4e38-85f3-aa02e6790de5" -e "51363990-425a190c-98d3-4207-b872-4dd5247173b8"
